services:
  pacheco_torres:
    container_name: pacheco_torres
    image: papelaria_pacheco_torres/pacheco_torres:1.0.0
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
    env_file:
      - .env

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - .env

  n8n:
    image: n8nio/n8n
    ports:
      - '5678:5678'
    environment:
      GENERIC_TIMEZONE: Americas/Sao_Paulo

  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api
    restart: always
    ports:
      - '8081:8081'
    env_file:
      - .env
